let aa=window.location.host,c=document.getElementById("canvas"),d=c.getContext("2d"),ba=document.getElementById("form"),e=document.getElementById("message"),[f,h,k,n,p,t,u,v,w,x,y,z,ca,da,ea,fa,ha,ia,ja,ka]=[document.getElementById("bLeft"),document.getElementById("bRight"),document.getElementById("bUp"),document.getElementById("bDown"),document.getElementById("bShift"),document.getElementById("ChatMessage"),document.getElementById("Notification"),document.getElementById("cb1"),document.getElementById("cb2"),
document.getElementById("cb3"),document.getElementById("cb4"),document.getElementById("cb5"),document.getElementById("cb6"),document.getElementById("cb1t"),document.getElementById("cb2t"),document.getElementById("cb3t"),document.getElementById("cb4t"),document.getElementById("cb5t"),document.getElementById("cb6t"),document.getElementById("message")];
ba.addEventListener("submit",a=>{a.preventDefault();e.value&&(a=e.value,null!==a&&(B.send(JSON.stringify(["message",a.slice(0,128).toString()])),e.value=""))});if(0<=window.navigator.appVersion.indexOf("Android")||0<=window.navigator.appVersion.indexOf("iOS"))f.removeAttribute("hidden"),h.removeAttribute("hidden"),k.removeAttribute("hidden"),n.removeAttribute("hidden"),p.removeAttribute("hidden");d.font="bold 16px Calibri, Carlito, sans-serif";let B=new WebSocket(`wss://${aa}`);
var C={},D=v.checked,E=w.checked,la=x.checked,ma=y.checked,na=z.checked,F=ca.checked,oa=da.checked,pa=ea.checked,qa=fa.checked,ra=ha.checked,sa=ia.checked,G=ja.checked,H=0,ta=0,I=0,J=0,K=!1,L=60,M=(a,l,b,g="#FFFFFF",m=!1,q=16,O=!0,r=!1)=>{m&&(d.fillStyle="#00000080",d.fillRect(l-("center"==d.textAlign?d.measureText(a).width/2:0),b-12,d.measureText(a).width,16));d.font=`${O?"bold ":""}${r?"italic ":""}${q}px Calibri`;d.fillStyle=g;m=d.fillStyle;q="FF";void 0!==m[6]&&void 0!==m[7]&&(q=m[6]+m[7]);d.fillStyle=
`#000000${q}`;d.fillText(a,l+1,b+1);d.fillStyle=g;d.fillText(a,l,b)},N={},P="",ua=0,va=0,Q=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],R=[],U=0,V="",W=0,wa=!1,X=[],Y=["Made by dottych","github.com/dottych","youtube.com/@dottych","Discord: dotty#7939"],
Z="",xa={"#FF6969":"red","#69EE69":"green","#3369FF":"blue","#69FFFF":"cyan","#69FF69":"lime","#FFFF69":"yellow","#FFAA69":"orange","#6969FF":"purple","#FF69FF":"pink","#FFFFFF":"white","#000000":"black","#AAAAAA":"gray","#AA6969":"brown","#AA0000":"maroon"},ya=a=>{let l=a-H;L=1E3/l;H=a;d.clearRect(0,0,c.width,c.height);d.fillStyle="gray";d.fillRect(0,0,c.width,c.height);[D,E,la,ma,na,F,oa,pa,qa,ra,sa,G]=[v.checked,w.checked,x.checked,y.checked,z.checked,ca.checked,da.checked,ea.checked,fa.checked,
ha.checked,ia.checked,ja.checked];if(void 0!==Q[8])for(a=0;16>a;a++)for(var b=0;9>b;b++)if(0<Q[b][a])switch(Q[b][a]){case 1:d.fillStyle="#858585";d.fillRect(80*a,80*b,80,80);break;case 2:d.fillStyle="#909090";d.fillRect(80*a,80*b,80,80);break;case 3:d.fillStyle="#AAAAAA",d.fillRect(80*a,80*b,80,80)}for(a=0;a<X.length;a++)1>X[a][2]?X.splice(a,1):(d.fillStyle=`${X[a][3]}${1==X[a][2].toString(16).length?"0"+X[a][2].toString(16):X[a][2].toString(16)}`,d.fillRect(X[a][0]+4,X[a][1]+4,8,8),X[a][2]--);d.textAlign=
"center";for(a=0;a<Object.keys(N).length;a++)if(b=N[Object.keys(N)[a]],Object.keys(N)[a]!=P){var g=b.g;g=Math.floor(g+2/(5*l)*l*(b.x-g));var m=b.h;m=Math.floor(m+2/(5*l)*l*(b.y-m));b.g=b.x;b.h=b.y;d.beginPath();d.fillStyle=b.color;d.arc(g+8,m+8,8,0,2*Math.PI);d.fill();d.closePath();if(G){b=Object.keys(N)[a];var q=d.measureText(Object.keys(N)[a]).width/2,O=1280-d.measureText(Object.keys(N)[a]).width/2;M(b,Math.min(Math.max(g+8,q),O),Math.min(Math.max(m-16,16),704),"#FFFFFF",F)}}else d.beginPath(),
d.fillStyle="#AAAAAA",d.arc(b.x+8,b.y+8,9,0,2*Math.PI),d.fill(),d.closePath(),d.beginPath(),d.fillStyle=b.color,d.arc(b.x+8,b.y+8,8,0,2*Math.PI),d.fill(),d.closePath(),G&&(g=Object.keys(N)[a],m=d.measureText(Object.keys(N)[a]).width/2,q=1280-d.measureText(Object.keys(N)[a]).width/2,M(g,Math.min(Math.max(b.x+8,m),q),Math.min(Math.max(b.y-16,16),704),"#FFFFFF",F));[ua,va]=[void 0===N[P]?0:N[P].x,void 0===N[P]?0:N[P].y];let [,,r,A,,S,T]=[0,0,0,0,0,!1,!1];b=2/15*l;a=N[P];try{if(!ka.matches(":focus")){if(C[37]||
C.left||C[65])r=-b;if(C[39]||C.right||C[68])r=b;if(C[38]||C.j||C[87])A=-b;if(C[40]||C.i||C[83])A=b}if(a.x!==a.g)for(b=0;9>b;b++)for(g=0;16>g;g++)2<=Q[b][g]&&!S&&(S=a.x+r<80*g+80&&a.x+r+16>80*g&&a.y<80*b+80&&a.y+16>80*b);if(a.y!==a.h)for(b=0;9>b;b++)for(g=0;16>g;g++)2<=Q[b][g]&&!T&&(T=a.x<80*g+80&&a.x+16>80*g&&a.y+A<80*b+80&&a.y+A+16>80*b);S||(N[P].x=Math.min(Math.max(N[P].x+r,0),1264));T||(N[P].y=Math.min(Math.max(N[P].y+A,0),704));wa=C[16]||C.shift?!0:!1}catch(Ba){}d.textAlign="left";M("Balls Online",
16,16,"#EEEEEE");oa&&(M(`FPS: ${Math.ceil(L)}`,16,32,30>L?15>L?"red":"yellow":"lime",D),M(`Ping: ${isNaN(I)?0:I}ms`,16,48,100<I?250<I?"red":"yellow":"lime",D),M(`Status: ${0==B.readyState||3==B.readyState||2==B.readyState?"offline":"online"}`,16,64,0==B.readyState||3==B.readyState||2==B.readyState?"red":"lime",D),M(`Client run: ${Math.floor(H/1E3)}s`,16,96,"#AAAAFF",D),M(`Server run: ${Math.floor((ta+H)/1E3)}s`,16,112,"#AAAAFF",D),M("Version: 0.4.0",16,144,"#AAAAFF",D),M(`Platform: ${window.navigator.platform}`,
16,160,"#AAAAFF",D));pa&&(M("Info",192,16,"#EEEEEE"),M(`Client ID: ${P}`,192,32,"#DDDDDD",E),M(`Client X: ${Math.floor(void 0===N[P]?0:N[P].x)}`,192,48,"#DDDDDD",E),M(`Client Y: ${Math.floor(void 0===N[P]?0:N[P].y)}`,192,64,"#DDDDDD",E),M(`Players: ${Object.keys(N).length}`,192,96,"#DDDDDD",E));if(qa)for(M("Chat",384,16,"#EEEEEE"),a=0;a<R.length;a++)M(R[a],384,16*(a+2),a==R.length-1?`${"#DDDD"}${1==Math.round(U).toString(16).length?"0"+Math.round(U).toString(16):Math.round(U).toString(16)}`:"#DDDDDD",
la),221>U&&(U+=.1*l);M(Z,1024,16,"#EEEEEE",!1,16,!0,!0);if(ra)for(M("Player list",16,192,"#EEEEEE"),a=0;a<Object.keys(N).length;a++)b=N[Object.keys(N)[a]],M(`${Object.keys(N)[a]} - ${Math.round(b.x)}, ${Math.round(b.y)}`,16,192+16*(a+1),b.color,ma);sa&&0<W&&(M(V,(1280-d.measureText(V).width)/2,360,`#EEEEEE${255<W?"FF":(1==Math.round(W).toString(16).length?"0":"")+Math.round(W).toString(16)}`,na),W-=.1*l);requestAnimationFrame(ya)},za;B.addEventListener("open",()=>{console.log("Connected to server")});
B.addEventListener("message",a=>{a=JSON.parse(a.data);switch(a[0]){case "id":P=a[1];null!==window.localStorage.getItem("name")&&B.send(JSON.stringify(["message",`/name ${window.localStorage.getItem("name")}`]));null!==window.localStorage.getItem("color")&&B.send(JSON.stringify(["message",`/color ${window.localStorage.getItem("color")}`]));break;case "time":ta=a[1];break;case "spawn":N[a[1]]={x:a[2],y:a[3],g:0,h:0,color:a[4]};break;case "despawn":delete N[a[1]];break;case "move":N[a[1]].x=a[2];N[a[1]].y=
a[3];break;case "ping":K=!1;J=0;I=Math.ceil(performance.now()-za);break;case "map":Q=a[1];break;case "message":R.push(`${a[1]}: ${a[2]}`);8<R.length&&R.shift();U=document.hasFocus()?0:221;t.currentTime=0;t.play();break;case "rename":let l=N[a[1]];delete N[a[1]];a[1]==P&&(P=a[2],window.localStorage.setItem("name",a[2]));N[a[2]]={x:l.x,y:l.y,g:0,h:0,color:l.color};break;case "restart":location.reload();break;case "notification":V=a[1];W=510;t.pause();u.currentTime=0;u.play();break;case "draw":X.push([a[1],
a[2],255,a[3]]);break;case "audio":console.log("Audio loading from "+a[1]);(new Audio(a[1])).play();break;case "color":a[1]==P&&window.localStorage.setItem("color",xa[a[2]]),N[a[1]].color=a[2]}});window.addEventListener("keydown",a=>{C[a.keyCode]=!0;console.log(a.keyCode)});window.addEventListener("keyup",a=>{C[a.keyCode]=!1});k.addEventListener("touchstart",()=>{C.j=!0});n.addEventListener("touchstart",()=>{C.i=!0});f.addEventListener("touchstart",()=>{C.left=!0});
h.addEventListener("touchstart",()=>{C.right=!0});p.addEventListener("touchstart",()=>{C.shift=!0});k.addEventListener("touchend",()=>{C.j=!1});n.addEventListener("touchend",()=>{C.i=!1});f.addEventListener("touchend",()=>{C.left=!1});h.addEventListener("touchend",()=>{C.right=!1});p.addEventListener("touchend",()=>{C.shift=!1});
setInterval(()=>{try{B.readyState==WebSocket.CLOSED||ua==N[P].x&&va==N[P].y||(B.send(JSON.stringify(["move",Math.round(N[P].x),Math.round(N[P].y)])),wa&&B.send(JSON.stringify(["draw"])))}catch(a){}},50);let Aa=setInterval(()=>{B.readyState!=WebSocket.CLOSED?(K?10<J&&(B.close(),location.reload(),clearInterval(Aa)):(B.send(JSON.stringify(["ping"])),K=!0,za=performance.now()),J++):(location.reload(),clearInterval(Aa))},1E3);Z=Y[0];setInterval(()=>{Z=Y[Math.floor(Math.random()*Y.length)]},5E3);requestAnimationFrame(ya);
