let aa=window.location.host,c=document.getElementById("canvas"),d=c.getContext("2d"),ba=document.getElementById("form"),e=document.getElementById("message"),[f,h,k,n,r,u,v,w,x,y,z,ca,da,ea,fa,ha,ia,ja,ka,la,ma]=[document.getElementById("bLeft"),document.getElementById("bRight"),document.getElementById("bUp"),document.getElementById("bDown"),document.getElementById("bShift"),document.getElementById("ChatMessage"),document.getElementById("Notification"),document.getElementById("cb1"),document.getElementById("cb2"),
document.getElementById("cb3"),document.getElementById("cb4"),document.getElementById("cb5"),document.getElementById("cb6"),document.getElementById("cb1t"),document.getElementById("cb2t"),document.getElementById("cb3t"),document.getElementById("cb4t"),document.getElementById("cb5t"),document.getElementById("cb6t"),document.getElementById("cb7t"),document.getElementById("message")];
ba.addEventListener("submit",a=>{a.preventDefault();e.value&&(a=e.value,null!==a&&(A.send(JSON.stringify(["message",a.slice(0,128).toString()])),e.value=""))});if(0<=window.navigator.appVersion.indexOf("Android")||0<=window.navigator.appVersion.indexOf("iOS"))f.removeAttribute("hidden"),h.removeAttribute("hidden"),k.removeAttribute("hidden"),n.removeAttribute("hidden"),r.removeAttribute("hidden");d.font="bold 16px Calibri, Carlito, sans-serif";let A=new WebSocket(`wss://${aa}`);
var B={},C=w.checked,D=x.checked,na=y.checked,oa=z.checked,pa=ca.checked,E=da.checked,qa=ea.checked,ra=fa.checked,sa=ha.checked,ta=ia.checked,ua=ja.checked,F=ka.checked,G=la.checked,H=0,va=0,I=0,J=0,K=!1,L=60,M=(a,l,b,g="#FFFFFF",m=!1,t=16,P=!0,p=!1)=>{m&&(d.fillStyle="#00000080",d.fillRect(l-("center"==d.textAlign?d.measureText(a).width/2:0),b-12,d.measureText(a).width,16));d.font=`${P?"bold ":""}${p?"italic ":""}${t}px Calibri`;d.fillStyle=g;m=d.fillStyle;t="FF";void 0!==m[6]&&void 0!==m[7]&&(t=
m[6]+m[7]);d.fillStyle=`#000000${t}`;d.fillText(a,l+1,b+1);d.fillStyle=g;d.fillText(a,l,b)},N={},O="",wa=0,xa=0,Q=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],R=[],S=0,V="",W=0,ya=!1,X=[],Y=["Made by dottych","github.com/dottych","youtube.com/@dottych",
"Discord: dotty#7939"],Z="",za={"#FF6969":"red","#69EE69":"green","#3369FF":"blue","#69FFFF":"cyan","#69FF69":"lime","#FFFF69":"yellow","#FFAA69":"orange","#6969FF":"purple","#FF69FF":"pink","#FFFFFF":"white","#000000":"black","#AAAAAA":"gray","#AA6969":"brown","#AA0000":"maroon","#0000AA":"indigo"},Aa=a=>{let l=a-H;L=1E3/l;H=a;d.clearRect(0,0,c.width,c.height);d.fillStyle="gray";d.fillRect(0,0,c.width,c.height);[C,D,na,oa,pa,E,qa,ra,sa,ta,ua,F,G]=[w.checked,x.checked,y.checked,z.checked,ca.checked,
da.checked,ea.checked,fa.checked,ha.checked,ia.checked,ja.checked,ka.checked,la.checked];if(void 0!==Q[8])for(a=0;16>a;a++)for(var b=0;9>b;b++)if(0<Q[b][a])switch(Q[b][a]){case 1:d.fillStyle="#858585";d.fillRect(80*a,80*b,80,80);break;case 2:d.fillStyle="#909090";d.fillRect(80*a,80*b,80,80);break;case 3:d.fillStyle="#AAAAAA",d.fillRect(80*a,80*b,80,80)}if(G)for(a=0;a<X.length;a++)1>X[a][2]?X.splice(a,1):(d.fillStyle=`${X[a][3]}${1==X[a][2].toString(16).length?"0"+X[a][2].toString(16):X[a][2].toString(16)}`,
d.fillRect(X[a][0]+4,X[a][1]+4,8,8),X[a][2]--);else X=[];d.textAlign="center";for(a=0;a<Object.keys(N).length;a++)if(b=N[Object.keys(N)[a]],Object.keys(N)[a]!=O){var g=b.g;g=Math.floor(g+2/(5*l)*l*(b.x-g));var m=b.h;m=Math.floor(m+2/(5*l)*l*(b.y-m));b.g=b.x;b.h=b.y;d.beginPath();d.fillStyle=b.color;d.arc(g+8,m+8,8,0,2*Math.PI);d.fill();d.closePath();if(F){b=Object.keys(N)[a];var t=d.measureText(Object.keys(N)[a]).width/2,P=1280-d.measureText(Object.keys(N)[a]).width/2;M(b,Math.min(Math.max(g+8,t),
P),Math.min(Math.max(m-16,16),704),"#FFFFFF",E)}}else d.beginPath(),d.fillStyle="#AAAAAA",d.arc(b.x+8,b.y+8,9,0,2*Math.PI),d.fill(),d.closePath(),d.beginPath(),d.fillStyle=b.color,d.arc(b.x+8,b.y+8,8,0,2*Math.PI),d.fill(),d.closePath(),F&&(g=Object.keys(N)[a],m=d.measureText(Object.keys(N)[a]).width/2,t=1280-d.measureText(Object.keys(N)[a]).width/2,M(g,Math.min(Math.max(b.x+8,m),t),Math.min(Math.max(b.y-16,16),704),"#FFFFFF",E));[wa,xa]=[void 0===N[O]?0:N[O].x,void 0===N[O]?0:N[O].y];let [,,p,q,,
T,U]=[0,0,0,0,0,!1,!1];b=2/15*l;a=N[O];try{if(!ma.matches(":focus")){if(B[37]||B.left||B[65])p=-b;if(B[39]||B.right||B[68])p=b;if(B[38]||B.j||B[87])q=-b;if(B[40]||B.i||B[83])q=b}p=0!==q?p/Math.sqrt(2):p;q=0!==p?q/Math.sqrt(2):q;if(a.x!==a.g)for(b=0;9>b;b++)for(g=0;16>g;g++)2<=Q[b][g]&&!T&&(T=a.x+p<80*g+80&&a.x+p+16>80*g&&a.y<80*b+80&&a.y+16>80*b);if(a.y!==a.h)for(b=0;9>b;b++)for(g=0;16>g;g++)2<=Q[b][g]&&!U&&(U=a.x<80*g+80&&a.x+16>80*g&&a.y+q<80*b+80&&a.y+q+16>80*b);T||(N[O].x=Math.min(Math.max(N[O].x+
p,0),1264));U||(N[O].y=Math.min(Math.max(N[O].y+q,0),704));ya=B[16]||B.shift?!0:!1}catch(Da){}d.textAlign="left";M("Balls Online",16,16,"#EEEEEE");qa&&(M(`FPS: ${Math.ceil(L)}`,16,32,30>L?15>L?"red":"yellow":"lime",C),M(`Ping: ${isNaN(I)?0:I}ms`,16,48,100<I?250<I?"red":"yellow":"lime",C),M(`Status: ${0==A.readyState||3==A.readyState||2==A.readyState?"offline":"online"}`,16,64,0==A.readyState||3==A.readyState||2==A.readyState?"red":"lime",C),M(`Client run: ${Math.floor(H/1E3)}s`,16,96,"#AAAAFF",C),
M(`Server run: ${Math.floor((va+H)/1E3)}s`,16,112,"#AAAAFF",C),M("Version: 0.4.1",16,144,"#AAAAFF",C),M(`Platform: ${window.navigator.platform}`,16,160,"#AAAAFF",C));ra&&(M("Info",192,16,"#EEEEEE"),M(`Client ID: ${O}`,192,32,"#DDDDDD",D),M(`Client X: ${Math.floor(void 0===N[O]?0:N[O].x)}`,192,48,"#DDDDDD",D),M(`Client Y: ${Math.floor(void 0===N[O]?0:N[O].y)}`,192,64,"#DDDDDD",D),M(`Players: ${Object.keys(N).length}`,192,96,"#DDDDDD",D));if(sa)for(M("Chat",384,16,"#EEEEEE"),a=0;a<R.length;a++)M(R[a],
384,16*(a+2),a==R.length-1?`${"#DDDD"}${1==Math.round(S).toString(16).length?"0"+Math.round(S).toString(16):Math.round(S).toString(16)}`:"#DDDDDD",na),221>S&&(S+=.1*l);M(Z,1024,16,"#EEEEEE",!1,16,!0,!0);if(ta)for(M("Player list",16,192,"#EEEEEE"),a=0;a<Object.keys(N).length;a++)b=N[Object.keys(N)[a]],M(`${Object.keys(N)[a]} - ${Math.round(b.x)}, ${Math.round(b.y)}`,16,192+16*(a+1),b.color,oa);ua&&0<W&&(M(V,(1280-d.measureText(V).width)/2,360,`#EEEEEE${255<W?"FF":(1==Math.round(W).toString(16).length?
"0":"")+Math.round(W).toString(16)}`,pa),W-=.1*l);requestAnimationFrame(Aa)},Ba;A.addEventListener("open",()=>{console.log("Connected to server")});
A.addEventListener("message",a=>{a=JSON.parse(a.data);switch(a[0]){case "id":O=a[1];null!==window.localStorage.getItem("name")&&A.send(JSON.stringify(["message",`/name ${window.localStorage.getItem("name")}`]));null!==window.localStorage.getItem("color")&&A.send(JSON.stringify(["message",`/color ${window.localStorage.getItem("color")}`]));break;case "time":va=a[1];break;case "spawn":N[a[1]]={x:a[2],y:a[3],g:0,h:0,color:a[4]};break;case "despawn":delete N[a[1]];break;case "move":N[a[1]].x=a[2];N[a[1]].y=
a[3];break;case "ping":K=!1;J=0;I=Math.ceil(performance.now()-Ba);break;case "map":Q=a[1];break;case "message":R.push(`${a[1]}: ${a[2]}`);8<R.length&&R.shift();S=document.hasFocus()?0:221;u.currentTime=0;u.play();break;case "rename":let l=N[a[1]];delete N[a[1]];a[1]==O&&(O=a[2],window.localStorage.setItem("name",a[2]));N[a[2]]={x:l.x,y:l.y,g:0,h:0,color:l.color};break;case "restart":location.reload();break;case "notification":V=a[1];W=510;u.pause();v.currentTime=0;v.play();break;case "draw":document.hasFocus()&&
G&&X.push([a[1],a[2],255,a[3]]);break;case "audio":console.log("Audio loading from "+a[1]);(new Audio(a[1])).play();break;case "color":a[1]==O&&window.localStorage.setItem("color",za[a[2]]),N[a[1]].color=a[2]}});window.addEventListener("keydown",a=>{B[a.keyCode]=!0});window.addEventListener("keyup",a=>{B[a.keyCode]=!1});k.addEventListener("touchstart",()=>{B.j=!0});n.addEventListener("touchstart",()=>{B.i=!0});f.addEventListener("touchstart",()=>{B.left=!0});
h.addEventListener("touchstart",()=>{B.right=!0});r.addEventListener("touchstart",()=>{B.shift=!0});k.addEventListener("touchend",()=>{B.j=!1});n.addEventListener("touchend",()=>{B.i=!1});f.addEventListener("touchend",()=>{B.left=!1});h.addEventListener("touchend",()=>{B.right=!1});r.addEventListener("touchend",()=>{B.shift=!1});
setInterval(()=>{try{A.readyState==WebSocket.CLOSED||wa==N[O].x&&xa==N[O].y||(A.send(JSON.stringify(["move",Math.round(N[O].x),Math.round(N[O].y)])),ya&&A.send(JSON.stringify(["draw"])))}catch(a){}},50);let Ca=setInterval(()=>{A.readyState!=WebSocket.CLOSED?(K?10<J&&(A.close(),location.reload(),clearInterval(Ca)):(A.send(JSON.stringify(["ping"])),K=!0,Ba=performance.now()),J++):(location.reload(),clearInterval(Ca))},1E3);Z=Y[0];setInterval(()=>{Z=Y[Math.floor(Math.random()*Y.length)]},5E3);requestAnimationFrame(Aa);
